export const home = [
  {
    id: 1,
    title: "Modern 3-Bedroom Home",
    description:
      "A beautiful modern house with 3 bedrooms, 2 bathrooms, and a spacious backyard.",
    price: "10 ETH",
    location: " New York, NY 1019",
    size: "2,000 sqft",
    bedrooms: 3,
    bathrooms: 2,
    pictures: require("./assets/images/h1.jpg"),
    year: 2009,
    tor: "roll",
  },
  {
    id: 2,
    title: "Luxurious 5-Bedroom Villa",
    description:
      "A stunning villa featuring 5 bedrooms, a swimming pool, and breathtaking ocean views.",
    price: "40 ETH",
    location: "Malibu, CA",
    size: "5,500 sqft",
    bedrooms: 5,
    bathrooms: 4,
    pictures: require("./assets/images/h2.jpg"),
    year: 2003,
    tor: "studio",
  },
  {
    id: 3,
    title: "Cozy 2-Bedroom Apartment",
    description:
      "A cozy apartment in a prime downtown location, perfect for small families or professionals.",
    price: "20 ETH",
    location: "Austin, TX",
    size: "1,200 sqft",
    bedrooms: 2,
    bathrooms: 1,
    pictures: require("./assets/images/h3.jpg"),
    year: 2006,
    tor: "condo",
  },
  {
    id: 4,
    title: "Charming Cottage",
    description:
      "A charming 2-bedroom cottage surrounded by nature, offering peace and tranquility.",
    price: "$175,000",
    location: "Asheville, NC",
    size: "1,000 sqft",
    bedrooms: 2,
    bathrooms: 1,
    pictures: require("./assets/images/h4.jpg"),
    year: 2014,
    tor: "suite",
  },
  {
    id: 5,
    title: "Urban Studio Apartment",
    description:
      "A stylish studio apartment located in the heart of downtown, with modern amenities.",
    price: "14 ETH",
    location: "New York, NY",
    size: "800 sqft",
    bedrooms: 1,
    bathrooms: 1,
    pictures: require("./assets/images/h5.jpg"),
    year: 2006,
    tor: "htl",
  },
  {
    id: 6,
    title: "Family 4-Bedroom House",
    description:
      "A perfect home for families, featuring 4 bedrooms, 3 bathrooms, and a spacious garden.",
    price: "24 ETH",
    location: "Denver, CO",
    size: "2,500 sqft",
    bedrooms: 4,
    bathrooms: 3,
    year: 2019,
    tor: "gallery",
    pictures: require("./assets/images/h6.jpg"),
  },
  {
    id: 7,
    title: "Elegant Penthouse",
    description:
      "A luxurious penthouse with panoramic city views, a private terrace, and high-end finishes.",
    price: "16 ETH",
    location: "Miami, FL",
    size: "4,000 sqft",
    bedrooms: 3,
    bathrooms: 3,
    year: 2019,
    tor: "condo",
    pictures: require("./assets/images/h7.jpg"),
  },
  {
    id: 8,
    title: "Rustic Farmhouse",
    description:
      "A rustic farmhouse set on 10 acres, featuring 4 bedrooms, a barn, and stunning countryside views.",
    price: "19 ETH",
    location: "Nashville, TN",
    size: "3,000 sqft",
    bedrooms: 4,
    bathrooms: 2,
    year: 2022,
    tor: "gallery",
    pictures: require("./assets/images/h8.jpg"),
  },
];
