import type { Metadata } from "next";
import { Hepta_Slab } from "next/font/google";
import "./globals.css";
import Provider from "./provider";

const heptaslab = Hepta_Slab({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "SaaS Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heptaslab.className}>
        {" "}
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
